"""Render app/resources/icon.png — the single source for the Dock icon, the
packaged macOS/Windows icons (electron-builder points at this file), and the
site favicons. Regenerated by `npm run build:icon` on every package, so this
file IS the icon; the PNG is an artifact.

    engine/.venv/bin/python tools/launcher/make-icon.py

DESIGN (settled 2026-08-07, replacing the sheet+tick+sparkle tile). The icon is
a piece of LEDGER PAPER carrying the product's own review tick:

  - **Ledger paper is the profession's texture.** Feint rows, an orange margin
    rule, double money columns at the right — instantly "accounting" to a CPA,
    and nothing else in a Dock looks like it. The old tile read as a generic
    tasks app precisely because a sheet with a tick belongs to everyone.
  - **The cream tile is deliberate contrast.** Every neighbouring tile is dark
    (the Ledger Labs monogram, ProBooks, most of a working Dock) — the light
    tile is findable peripherally before it is even read.
  - **The green review tick is CONTENT and does not follow the brand.** It is
    appearance.TICK_COLOR exactly — the same green a preparer sees on the page
    and in the exported PDF. Ledger Green (#2D9148) was the obvious brand
    substitute and is deliberately not used: the icon earns recognition by
    showing the same mark the product makes.
  - **The margin rule carries the Ledger Labs accent** (Signal Orange), so the
    family shows without borrowing the monogram.
  - **The sparkle says an agent works here** — kept small, top-left, clear of
    the rules. A four-point star with a pinched waist; a robot glyph would date
    badly and say "chatbot" rather than "this thing works on your binder".

A two-tone family-tick concept (orange/cream ribbon tick on teal, echoing the
LL monogram) was rendered, iterated and REJECTED: strongest at 32px, but it is
still fundamentally a checkmark — the generic-icon complaint survives it — and
it breaks the tick-is-content rule above. The comparison sheets live in the
session record of 2026-08-07.
"""

from pathlib import Path

from PIL import Image, ImageDraw

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "app" / "resources" / "icon.png"
S = 1024

# Ledger Labs brand kit — _studio/Ledger Labs Brand Kit/tokens/palette.json.
VELLUM = (245, 236, 214, 255)      # Vellum #F5ECD6 — the paper itself
ORANGE = (232, 145, 58, 255)       # Signal Orange #E8913A — margin rule, sparkle
TEAL_FEINT = (29, 67, 78, 42)      # Deep Teal at feint strength — ruled rows
TEAL_COLUMN = (29, 67, 78, 80)     # ...and column weight
# The tick is CONTENT — appearance.TICK_COLOR exactly. See the header.
GREEN = (33, 140, 33, 255)


def sparkle(d: ImageDraw.ImageDraw, cx: float, cy: float, r: float, fill) -> None:
    w = r * 0.30
    d.polygon(
        [
            (cx, cy - r), (cx + w, cy - w), (cx + r, cy), (cx + w, cy + w),
            (cx, cy + r), (cx - w, cy + w), (cx - r, cy), (cx - w, cy - w),
        ],
        fill=fill,
    )


def main() -> None:
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # FULL BLEED, same rationale as the previous icon: macOS 26 composites
    # icons into a system container, so a self-inset icon gets inset twice and
    # shows a pale frame. Fill the canvas, let the system mask; the radius here
    # is smaller than the system's so the mask trims our corners, and Windows —
    # which does not mask — gets a normal rounded tile.
    d.rounded_rectangle([0, 0, S, S], radius=200, fill=VELLUM)

    # Feint rows. They vanish below ~64px, which is fine — the tile, the margin
    # rule and the tick carry the small sizes; the rows carry the big ones.
    for i in range(8):
        y = 150 + i * 106
        d.line([(64, y), (960, y)], fill=TEAL_FEINT, width=7)

    # The margin rule — the classic red line of ledger paper, in the brand's
    # orange. Left, where a century of stationery put it.
    d.line([(178, 64), (178, 960)], fill=ORANGE, width=13)

    # Double money columns, far right, behind nothing.
    for x in (836, 872):
        d.line([(x, 64), (x, 960)], fill=TEAL_COLUMN, width=8)

    # The review tick. Heavier than the UI draws it: at 32px a product-weight
    # stroke greys out into the paper.
    d.line([(276, 596), (446, 772), (776, 320)], fill=GREEN, width=110, joint="curve")

    sparkle(d, 356, 206, 64, ORANGE)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
